name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"
      - run: deno check src/
      - run: deno lint src/
      - run: deno fmt --check src/
      - run: deno test --allow-read --allow-write --allow-env --allow-run --allow-ffi --allow-sys --unstable-worker-options
